---
- name: Install git
  homebrew:
    name: git

- name: Set .gitignore file
  copy: src=files/.gitignore_global dest=~/

- name: Set .gitconfig
  copy: src=files/.gitconfig dest=~/

- name: Set .git-completion
  copy: src=files/.git-completion dest=~/

- name: reload .git-completion
  shell: echo 'source ~/.git-completion.bash' >> ~/.bashrc
