---
- name: Install lua
  homebrew:
    name: lua

- name: Install Vim
  shell: brew install macvim-dev/macvim/macvim --HEAD

- name: Link Macvim to vim
  shell: brew link --overwrite macvim

- name: Create .vim directory
  file: path=~/.vim/colors state=directory

- name: Git clone hybird
  git: repo=https://github.com/w0ng/vim-hybrid dest=~/vim-hybrid

- name: Move settings file
  shell: mv ~/vim-hybrid/colors/hybrid.vim ~/.vim/colors

- name: Remove hibird repository
  shell: rm -rf ~/vim-hybrid

- name: Set .vimrc
  copy: src=files/.vimrc dest=~/

- name: Create directory for xx.vim
  file:
    path: ~/.vim/after/ftplugin/go.vim
    mode: 0755
    state: directory

- name: Set go.vim
  copy: src=files/go.vim dest=~/.vim/after/ftplugin/go.vim
